name: Build Efikcoin Wallet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_android:
    name: Compile Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Global EAS CLI
        run: npm install -g eas-cli

      - name: Force Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Trigger Production EAS Build
        run: eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
